<!--
Copyright © 2016 Wyomind. All rights reserved.
See LICENSE.txt for license details.
-->
<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Category filter type'); ?></h4>
    </div>
    <div class="fieldset" id="category-type">
        <div class="main-box">
            <script>
                document.observe('dom:loaded', function () {
                    if ($('simplegoogleshopping_category_filter').value == 1) {
                        $('category_filter_0').checked = false;
                        $('category_filter_1').checked = true;
                    } else {
                        $('category_filter_0').checked = true;
                        $('category_filter_1').checked = false;
                    }
                    $$('.category_filter').each(function (r) {
                        r.observe('click', function () {
                            $('simplegoogleshopping_category_filter').value = r.value;
                        });
                    });

                    if ($('simplegoogleshopping_category_type').value == 1) {
                        $('category_type_0').checked = false;
                        $('category_type_1').checked = true;
                        $('category_type_2').checked = false;
                    } else if ($('simplegoogleshopping_category_type').value == 2) {
                        $('category_type_0').checked = false;
                        $('category_type_1').checked = false;
                        $('category_type_2').checked = true;
                    } else {
                        $('category_type_0').checked = true;
                        $('category_type_1').checked = false;
                        $('category_type_2').checked = false;
                    }
                    $$('.category_type').each(function (r) {
                        r.observe('click', function () {
                            $('simplegoogleshopping_category_type').value = r.value;
                        });
                    });
                });
            </script>
            <input type="radio" value="1" name="category_filter" class="category_filter" id="category_filter_1" /> 
            <?php echo $this->__("<b>Include</b> all products from the selected categories."); ?><br/>
            <input type="radio" value="0" name="category_filter" class="category_filter" id="category_filter_0" /> 
            <?php echo $this->__("<b>Exclude</b> all products from the selected categories."); ?><br/>
            <div style="padding:5px 0 0 0">
                <b>Based on </b><br/>
                <input type="radio" value="0" name="category_type" class="category_type" id="category_type_0"/> 
                <label for="category_type_0"><b>Product</b> categories only<br/></label>
                <input type="radio" value="1" name="category_type" class="category_type" id="category_type_1"/> 
                <label for="category_type_1"><b>Product and parent</b> categories<br/></label>
                <input type="radio" value="2" name="category_type" class="category_type" id="category_type_2"/> 
                <label for="category_type_2"><b>Parent</b> categories only<br/></label>                  
            </div>
        </div>
    </div>
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend">
            <?php echo $this->__('Category selection and mapping'); ?>
        </h4>
    </div>
    <div class="fieldset category-selector" id="category-selector">
        <div id="taxonomy-box">
            <b><?php echo Mage::helper('simplegoogleshopping')->__("Google Taxonomy source : ") ?></b>
            <select id="googleshopping_taxonomy" name="datafeed_taxonomy">
                <?php
                $io = new Varien_Io_File();
                $array = $this->dirFiles($io->getCleanPath(Mage::getBaseDir() . "/lib/Wyomind/Google/Taxonomies/"));

                foreach ($array as $key => $file) {
                    if (Mage::registry('simplegoogleshopping_data')
                                    ->getGoogleshoppingTaxonomy() == "/lib/Wyomind/Google/Taxonomies/" . $file) {
                        $selected = "selected";
                    } else {
                        $selected = "";
                    }

                    echo "<option value='" . "/lib/Wyomind/Google/Taxonomies/" . $file . "' $selected>"
                    . basename(str_replace('.txt', null, $file)) . "</option>";
                }
                ?> 
            </select> 
        </div>
        <br/>
        
        <span id='note' style='margin-left:10px;'><?php echo $this->__("* If you do not select any category, all products will be exported"); ?></span>
        <textarea style="display:none" id="cat-json-tree"><?php echo $this->getJsonTree(); ?></textarea>

        <script>
            SGS_categories.autoCompleteUrl = "<?php echo $this->getUrl('*/*/taxonomy'); ?>";
            // load selected categories
            SGS_categories.init();
            document.observe('click', function (evt) {
                var elt = evt.element();
                if (elt.hasClassName('tv-switcher')) {
                    if (elt.hasClassName('closed')) {
                        elt.removeClassName('closed');
                        elt.addClassName('opened');
                        SGS_categories.displayChildren(SGS_categories.tree[elt.id], "main-cat-" + elt.id);
                    } else if (elt.hasClassName('opened')) {
                        elt.addClassName('closed');
                        elt.removeClassName('opened');
                        $("main-cat-" + elt.id).up().select("ul").each(function (elt) {
                            elt.remove();
                        });
                    }
                } else if (elt.hasClassName("category")) {
                    elt.up().toggleClassName('selected');
                    SGS_categories.updateSelection();
                    SGS_categories.selectChildren(elt.id.replace("cat_id_", ""));
                } else if (elt.hasClassName("mapping")) {
                    SGS_categories.updateSelection();
                }
            });

            document.observe('keydown', function (evt) {
                var elt = evt.element();
                if (elt.hasClassName('mapping')) {
                    switch (evt.keyCode) {
                        case 35:
                            SGS_categories.updateChildrenMapping(elt.value, elt.id.replace('category_mapping_', ''));
                    }
                }
            });

        </script>
    </div>
</div>




