<!--
Copyright © 2016 Wyomind. All rights reserved.
See LICENSE.txt for license details.
-->
<?php
$id = Mage::app()->getRequest()->getParam('id');
$data = Mage::getModel('simplegoogleshopping/simplegoogleshopping')->load($id);
?>
<div class="entry-edit">
    <div class="entry-edit-head">
        <div class="all_checkbox"><input class="check_all" type="checkbox" id="all_type_id" /></div>
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Product type'); ?></h4>
    </div>
    <div class="fieldset" id="type-ids-selector">
        <div class="main-box">
            <div class="node">
                <div class="cat-box">
                    <input type="checkbox" id="type_id_simple" identifier="simple"/>
                    <label for="type_id_simple"><?php echo $this->__('Simple'); ?></label>
                </div>
            </div>
            <div class="node">
                <div class="cat-box">
                    <input type="checkbox" id="type_id_configurable" identifier="configurable"/>
                    <label for="configurable"><?php echo $this->__('Configurable'); ?></label>
                </div>
            </div>
            <div class="node">
                <div class="cat-box">
                    <input type="checkbox" id="type_id_bundle" identifier="bundle"/>
                    <label for="bundle"><?php echo $this->__('Bundle'); ?></label>
                </div>
            </div>
            <div class="node">
                <div class="cat-box">
                    <input type="checkbox" id="type_id_grouped" identifier="grouped"/>
                   <label for="grouped"> <?php echo $this->__('Grouped'); ?></label>
                </div>
            </div>
            <div class="node">
                <div class="cat-box">
                    <input type="checkbox" id="type_id_virtual" identifier="virtual"/>
                    <label for="virtual"><?php echo $this->__('Virtual'); ?></label>
                </div>
            </div>
            <div class="node">
                <div class="cat-box">
                    <input type="checkbox" id="type_id_downloadable" identifier="downloadable"/>
                   <label for="downloadable"> <?php echo $this->__('Downloadable'); ?></label>
                </div>
            </div>
            <?php if (version_compare(Mage::getVersion(), '1.10', '>=')) : ?>
            <div class="node">
                <div class="cat-box">
                    <input  type="checkbox" id="type_id_giftcard" identifier="giftcard"/>
                    <label for="giftcard"> <?php echo $this->__('Gift Card'); ?></label>
                </div>
            </div>
            <?php endif; ?>
            <input id="simplegoogleshopping_type_ids" name="simplegoogleshopping_type_ids" 
                   value="<?php echo $data->getSimplegoogleshoppingTypeIds(); ?>" 
                   class=" input-text required-entry" type="hidden"/>
        </div>
    </div>
</div>
<div class='entry-edit'>
    <div class="entry-edit-head">
        <div class="all_checkbox">
            <input class="check_all" type="checkbox" id="all_attribute_set"/>
        </div>
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Attribute Set'); ?></h4>
    </div>
    <div class="fieldset" id="attribute-sets-selector">
        <div class="main-box">
            <?php
            $entityTypeId = Mage::getModel('eav/entity')
                    ->setType('catalog_product')
                    ->getTypeId();
            $attributeSet = Mage::getModel('eav/entity_attribute_set')
                    ->getCollection()
                    ->setEntityTypeFilter($entityTypeId);
            ?>
        <?php foreach ($attributeSet as $set): ?>
            <div class="node">
                <div class="cat-box">
                    <input type="checkbox" id="attribute_set_<?php echo $set->getId(); ?>" 
                           identifier="<?php echo $set->getId(); ?>"/>
                    <label for="attribute_set_<?php echo $set->getId(); ?>"> <?php echo $set->getAttributeSetName(); ?></label>
                </div>
            </div>        
        <?php endforeach; ?>
            <input id="simplegoogleshopping_attribute_sets" name="simplegoogleshopping_attribute_sets" 
                   value="<?php echo $data->getSimplegoogleshoppingAttributeSets(); ?>" 
                   class=" input-text required-entry" type="hidden"/>          
        </div>
    </div>
</div>
<div class="entry-edit">
    <div class="entry-edit-head">
        <div class="all_checkbox"><input class="check_all" type="checkbox" id="all_visibility" /></div>
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Product visibility'); ?></h4>
    </div>
    <div class="fieldset " id="visibility-selector">
        <div class="main-box">
            <div class="node">
                <div class="cat-box"><input type="checkbox" id="visibility_1" identifier="1"/>
                    <label for="visibility_1"><?php echo $this->__('Not Visible Individually'); ?></label>
                </div>
            </div>
            <div class="node">
                <div class="cat-box"><input type="checkbox" id="visibility_2" identifier="2"/>
                     <label for="visibility_2"><?php echo $this->__('Catalog'); ?></label>
                </div>
            </div>
            <div class="node">
                <div class="cat-box"><input type="checkbox" id="visibility_3" identifier="3"/>
                    <label for="visibility_3"> <?php echo $this->__('Search'); ?></label>
                </div>
            </div>
            <div class="node">
                <div class="cat-box"><input type="checkbox" id="visibility_4" identifier="4"/>
                    <label for="visibility_4"> <?php echo $this->__('Catalog, Search'); ?></label>
                </div>
            </div>
            <input id="simplegoogleshopping_visibility" name="simplegoogleshopping_visibility" 
                   value="<?php echo $data->getSimplegoogleshoppingVisibility(); ?>" 
                   class=" input-text required-entry" type="hidden"/>
        </div>
    </div>
</div>
<div class='entry-edit'>
    <div class="entry-edit-head">
        <div class="all_checkbox"><input class="check_all" type="checkbox" id="all_attribute" /></div>
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Advanced filters'); ?></h4>
    </div>
    <div class="fieldset" id="attributes-selector">
        <?php
        $selectOutput = null;
        $attributesList = $this->getOrderedAttributeList();
        
        foreach ($attributesList as $attribute) {
            if (!empty($attribute['frontend_label'])) {
                $selectOutput.= "<option value='" . $attribute['attribute_code'] . "'>" 
                        . $attribute['frontend_label'] . "</option>";
            }
        }
        echo "<script>var _is_in_stock=[{\"label\":\"Yes\",\"value\":1},{\"label\":\"No\",\"value\":0}];\n"
        . "var _qty=[];\nvar _entity_id=[]; ";
        
        foreach ($attributesList as $attribute) {
            if (preg_match("/^[a-zA-Z0-9_]+$/", $attribute['attribute_code'])) {
                if (isset($attribute['attribute_id']) && !stristr($attribute['attribute_code'], "ugiftcert")) {
                    $options = $this->getAttributesOptions($attribute['attribute_id']);
                    
                    if ($attribute['attribute_code'] != 'location') {
                        echo "\n_" . $attribute['attribute_code'] . "=" . json_encode($options) . ";";
                    }
                }
            }
        }
        echo "</script>"; 
        $filtersConfig = Mage::getStoreConfig("simplegoogleshopping/system/filters"); ?>
        <?php for ($x = 0; $x <= $filtersConfig; $x++) : ?>
            <div class="node" id="node_<?php echo $x; ?>">
                <?php $size = "678px"; ?>
                <?php if (Mage::getStoreConfig("simplegoogleshopping/system/filters_sql")): ?>
                    <?php $size = "728px"; ?>
                <?php endif; ?>
                <div class="cat-box" 
                     style="width:<?php echo $size; ?>">
                    <input type="checkbox" id="attribute_<?php echo $x; ?>" identifier="<?php echo $x; ?>"/> 
                    <?php if (!Mage::getStoreConfig("simplegoogleshopping/system/filters_sql")): ?>
                        <?php $display = "none"; ?>
                    <?php else: ?>
                        <?php $display = ""; ?>
                    <?php endif; ?>
                <?php if ($x > 0): ?>
                    <select style="width:50px; display:<?php echo $display; ?>" 
                            disabled="disabled" class="statement-attribute" id="statement_attribute_<?php echo $x; ?>" 
                            onchange='simplegoogleshopping.setValues($("attributes-selector"))' >
                        <option value="AND">AND</option>
                        <option value="OR">OR</option>
                    </select>
                <?php else : ?>
                    <input type="text" id="statement_attribute_<?php echo $x; ?>" value="" class=" "
                           style="width:0px;visibility:hidden;margin-right:48px; display:<?php echo $display; ?>"/> 
                <?php endif; ?>
                    <select style="width:35px;display:none" disabled="disabled" class="parenthesis-open-attribute" 
                            id="parenthesis_open_attribute_<?php echo $x; ?>" 
                            onchange='simplegoogleshopping.setValues($("attributes-selector"))'>
                        <option value=""></option>
                        <option value="(">[</option>
                    </select>
                    <select style="width:300px" disabled="disabled" class="name-attribute" 
                            id="name_attribute_<?php echo $x; ?>" 
                            onchange='simplegoogleshopping.setValues($("attributes-selector"))' >
                        <?php echo $selectOutput; ?>
                    </select>
                    <select disabled="disabled" class="condition-attribute" 
                            id="condition_attribute_<?php echo $x; ?>" 
                            onchange='simplegoogleshopping.setValues($("attributes-selector"))' style="width:100px">
                        <option value="eq"><?php echo $this->__('=') ?></option>
                        <option value="gt"><?php echo $this->__('>') ?></option>
                        <option value="lt"><?php echo $this->__('<') ?></option>
                        <option value="gteq"><?php echo $this->__('&ge;') ?></option>
                        <option value="lteq"><?php echo $this->__('&le;') ?></option>
                        <option value="neq"><?php echo $this->__('&ne;') ?></option>
                        <option value="like"><?php echo $this->__('like') ?></option>
                        <option value="nlike"><?php echo $this->__('not like') ?></option>
                        <option value="null"><?php echo $this->__('is null') ?></option>
                        <option value="notnull"><?php echo $this->__('is not null') ?></option>
                        <option value="in"><?php echo $this->__('in') ?></option>
                        <option value="nin"><?php echo $this->__('not in') ?></option>
                    </select>
                    <select disabled="disabled" size="3" class="pre-value-attribute" 
                            id="pre-value-attribute_<?php echo $x; ?>" 
                            style="display:none;width:253px" multiple="multiple "></select>
                    <?php $advanced = null;?>
                    <?php if (Mage::getStoreConfig("simplegoogleshopping/system/filters_sql")): ?>
                        <?php $advanced = "advanced"; ?>
                    <?php endif; ?>
                    <input disabled="disabled" type='text' 
                           class="value-attribute <?php echo $advanced; ?>"  
                           id="value_attribute_<?php echo $x; ?>" 
                           style="width:250px" onkeyup='simplegoogleshopping.setValues($("attributes-selector"))'/>
                    <select style="width:35px; position: absolute; right: 9px; top: 0;display:none" 
                            disabled="disabled" class="parenthesis-close-attribute" 
                            id="parenthesis_close_attribute_<?php echo $x; ?>" 
                            onchange='simplegoogleshopping.setValues($("attributes-selector"))' >
                        <option value=""></option>
                        <option value=")">]</option>
                    </select>
                </div>
            </div>
        <?php endfor; ?>
    </div>
</div>